# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tbertozz <tbertozz@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/26 11:24:05 by tbertozz          #+#    #+#              #
#    Updated: 2022/08/26 12:29:03 by tbertozz         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	g++ -std=c++98 -Wall -Werror -Wextra main.cpp Zombie.cpp newZombie.cpp randomChump.cpp

clean:

fclean:
	rm -rf a.out

re: fclean all

.PHONY: all re clean fclean